[package]
name = "br-id"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-clipboard = "0.4.0"
clap = { version = "4.3.10", features = ["derive", "wrap_help"] }
rand = "0.8.5"
serde = "1.0.171"
